import 'dart:math';

import 'package:flutter/material.dart';
import 'package:intl/intl.dart';

import '../model/product_model.dart';
import 'db_helper.dart';

class SaveData {
  void save1000Product() async {
    final DBHelper dbHelper = DBHelper();
    await dbHelper.initDb();
    final Random random = Random();
    final List<String> drugs = [
      "Acetaminophen",
      "Albuterol",
      "Amoxicillin",
      "Atorvastatin",
      "Amlodipine",
      "Azithromycin",
      "Aspirin",
      "Metformin",
      "Ibuprofen",
      "Lisinopril",
      "Simvastatin",
      "Omeprazole",
      "Levothyroxine",
      "Hydrocodone/Acetaminophen",
      "Furosemide",
      "Gabapentin",
      "Warfarin",
      "Clopidogrel",
      "Metoprolol",
      "Insulin",
      "Sertraline",
      "Cetirizine",
      "Fluoxetine",
      "Prednisone",
      "Citalopram",
      "Doxycycline",
      "Tamsulosin",
      "Montelukast",
      "Ranitidine",
      "Clonazepam",
      "Loratadine",
      "Naproxen",
      "Tramadol",
      "Bisoprolol",
      "Valsartan",
      "Carvedilol",
      "Bupropion",
      "Allopurinol",
      "Ciproflaxin",
      "Meloxicam",
      "Pregabalin",
      "Lovastatin",
      "Duloxetine",
      "Fluticasone",
      "Acyclovir",
      "Nifedipine",
      "Gabapentin",
      "Dexamethasone",
      "Diazepam",
      "Verapamil",
      "Phenobarbital",
      "Chlorpheniramine",
      "Azathioprine",
      "Methylprednisolone",
      "Nitrofurantoin",
      "Metoclopramide",
      "Rivaroxaban",
      "Amiodarone",
      "Spironolactone",
      "Clonidine",
      "Atenolol",
      "Rosuvastatin",
      "Latanoprost",
      "Terazosin",
      "Ezetimibe",
      "Bismuth subsalicylate",
      "Liraglutide",
      "Dexamethasone",
      "Chlorpromazine",
      "Trazodone",
      "Phenytoin",
      "Anastrozole",
      "Mirtazapine",
      "Levocetirizine",
      "Nitroprusside",
      "Fentanyl",
      "Codeine",
      "Methadone",
      "Enalapril",
      "Olmesartan",
      "Diphenhydramine",
      "Sacubitril/Valsartan",
      "Sevelamer",
      "Buprenorphine",
      "Olanzapine",
      "Sotalol",
      "Paliperidone",
      "Esomeprazole",
      "Apixaban",
      "Insulin glargine",
      "Metformin",
      "Tadalafil",
      "Dulaglutide",
      "Azelastine",
      "Tizanidine",
      "Ropinirole",
      "Isosorbide dinitrate",
      "Nitroglycerin",
      "Acetazolamide",
      "Methotrexate",
      "Bicalutamide",
      "Beclomethasone",
      "Clobetasol",
      "Dexamethasone",
      "Gatifloxacin",
      "Imatinib",
      "Ketorolac",
      "Quetiapine",
      "Thiamine",
      "Valproate",
      "Phentermine",
      "Varenicline",
      "Rivastigmine",
      "Donepezil",
      "Simethicone",
      "Lidocaine",
      "Gabapentin",
      "Propranolol",
      "Epinphrine",
      "Clobetasone",
      "Folic acid",
      "Sodium bicarbonate",
      "Sucrose",
      "Hydrocortisone",
      "Sodium nitroprusside",
      "Carbidopa/Levodopa",
      "Ascorbic acid",
      "Diclofenac",
      "Topiramate",
      "Nortriptyline",
      "Fluconazole",
      "Metronidazole",
      "Theophylline",
      "Amphotericin B",
      "Adefovir",
      "Valganciclovir",
      "Diltiazem",
      "Mupirocin",
      "Phenylephrine",
      "Ranitidine",
      "Probenecid",
      "Dronabinol",
      "Paliperidone",
      "Bupropion",
      "Levothyroxine",
      "Metoprolol",
      "Olanzapine",
      "Tolterodine",
      "Lurasidone",
      "Gabapentin",
      "Lidocaine",
      "Olopatadine",
      "Sodium fluoride",
      "Isotretinoin",
      "Sulfamethoxazole/Trimethoprim",
      "Adalimumab",
      "Cyclosporine",
      "Tacrolimus",
      "Raloxifene",
      "Dextromethorphan",
      "Aminophylline",
      "Calcium carbonate",
      "Ferrous sulfate",
      "Promethazine",
      "Ipratropium",
      "Salmeterol",
      "Budesonide",
      "Lisinopril",
      "Ketoconazole",
      "Amlodipine",
      "Fenofibrate",
      "Bupropion",
      "Quetiapine",
      "Carbamazepine",
      "Phenytoin",
      "Thioridazine",
      "Chlorpromazine",
      "Methylphenidate",
      "Fexofenadine",
      "Ropinirole",
      "Sodium valproate",
      "Cholecalciferol",
      "Paroxetine",
      "Oxcarbazepine",
      "Cariprazine",
      "Atomoxetine",
      "Trifluoperazine",
      "Scopolamine",
      "Benztropine",
      "Estradiol",
      "Progesterone",
      "Desvenlafaxine",
      "Clonidine",
      "Dexamethasone",
      "Naltrexone",
      "Prazosin",
      "Betamethasone",
      "Misoprostol",
      "Olmesartan",
      "Diclofenac",
      "Estrone",
      "Estriol",
      "Testosterone",
      "Norgestimate",
      "Risedronate",
      "Raloxifene",
      "Conjugated estrogens",
      "Dapagliflozin",
      "Canagliflozin",
      "Empagliflozin",
      "Metolazone",
      "Glimepiride",
      "Glipizide",
      "Sitagliptin",
      "Linagliptin",
      "Exenatide",
      "Liraglutide",
      "Semaglutide",
      "Insulin lispro",
      "Insulin aspart",
      "Insulin detemir",
      "Insulin degludec",
      "Alogliptin",
      "Pioglitazone",
      "Rosiglitazone",
      "Saxagliptin",
      "Repaglinide",
      "Tolbutamide",
      "Chlorpropamide",
      "Meglitinide",
      "Gliclazide",
      "Troglitazone",
      "Pramlintide",
      "Bismuth subsalicylate",
      "Sodium phosphate",
      "Lactulose",
      "Docusate sodium",
      "Polyethylene glycol",
      "Bisacodyl",
      "Senna",
      "Metoclopramide",
      "Famotidine",
      "Cimetidine",
      "Doxylamine",
      "Diphenhydramine",
      "Hydroxyzine",
      "Loperamide",
      "Imodium",
      "Nexium",
      "Pantoprazole",
      "Rabeprazole",
      "Tamsulosin",
      "Finasteride",
      "Dutasteride",
      "Sildenfil",
      "Vardenafil",
      "Valsartan",
      "Irbesartan",
      "Candesartan",
      "Telmisartan",
      "Nimodipine",
      "Felodipine",
      "Amlodipine",
      "Diltiazem",
      "Nifedipine",
      "Verapamil",
      "Trandolapril",
      "Perindopril",
      "Ramipril",
      "Benazepril",
      "Eplerenone",
      "Spironolactone",
      "Amiodarone",
      "Digoxin",
      "Disopyramide",
      "Dronedarone",
      "Isosorbide dinitrate",
      "Nitroglycerin",
      "Amyl nitrite",
      "Candesartan",
      "Atorvastatin",
      "Rosuvastatin",
      "Simvastatin",
      "Lovastatin",
      "Pravastatin",
      "Fluvastatin",
      "Ezetimibe",
      "Cholestyramine",
      "Colesevelam",
      "Colestipol",
      "Niacin",
      "Omega-3 fatty acids",
      "Fenofibrate",
      "Omega-3 acid ethyl esters",
      "Propranolol",
      "Atenolol",
      "Metoprolol",
      "Bisoprolol",
      "Carvedilol",
      "Sotalol",
      "Nadolol",
      "Timolol",
      "Doxazosin",
      "Terazosin",
      "Prazosin",
      "Atenolol",
      "Amlodipine",
      "Diltiazem",
      "Nifedipine",
      "Verapamil",
      "Felodipine",
      "Sildenafil",
      "Tadalafil",
      "Vardenafil",
      "Finasteride",
      "Dutasteride",
      "Efinaconazole",
      "Fluconazole",
      "Ketoconazole",
      "Miconazole",
      "Voriconazole",
      "Caspofungin",
      "Anidulafungin",
      "Micafungin",
      "Nystatin",
      "Amphotericin B",
      "Terbinafine",
      "Itraconazole",
      "Posaconazole",
      "Clotrimazole",
      "Boric acid",
      "Fluorouracil",
      "Doxorubicin",
      "Cisplatin",
      "Carboplatin",
      "Methotrexate",
      "Vincristine",
      "Paclitaxel",
      "Docetaxel",
      "Etoposide",
      "Tamoxifen",
      "Letrozole",
      "Anastrozole",
      "Trastuzumab",
      "Rituximab",
      "Bevacizumab",
      "Nivolumab",
      "Pembrolizumab",
      "Atezolizumab",
      "Ipilimumab",
      "Tositumomab",
      "Alemtuzumab",
      "Elotuzumab",
      "Brentuximab vedotin",
      "Carfilzomib",
      "Bortezomib",
      "Thalidomide",
      "Lenalidomide",
      "Pomalidomide",
      "Acalabrutinib",
      "Ibrutinib",
      "Idelalisib",
      "Venetoclax",
      "Dasatinib",
      "Imatinib",
      "Nilotinib",
      "Bosutinib",
      "Tafasitamab",
      "Zanubrutinib",
      "Ofatumumab",
      "Obinutuzumab",
      "Ruxolitinib",
      "Fedratinib",
      "Clofarabine",
      "Nelarabine",
      "Etoposide",
      "Fludarabine",
      "Deferasirox",
      "Deferoxamine",
      "Iron sucrose",
      "Ferrous gluconate",
      "Rho(D) immune globulin",
      "Anti-D immunoglobulin",
      "Immunoglobulin",
      "Rituximab",
      "Adalimumab",
      "Infliximab",
      "Certolizumab pegol",
      "Golimumab",
      "Abatacept",
      "Tocilizumab",
      "Sarilumab",
      "Dupilumab",
      "Eculizumab",
      "Belimumab",
      "Natalizumab",
      "Ocrelizumab",
      "Alemtuzumab",
      "Bortezomib",
      "Carfilzomib",
      "Ixazomib",
      "Elotuzumab",
      "Daratumumab",
      "Tisagenlecleucel",
      "Axicabtagene ciloleucel",
      "Luspatercept",
      "Gilteritinib",
      "Crizotinib",
      "Alectinib",
      "Brigatinib",
      "Lorlatinib",
      "Entrectinib",
      "Trametinib",
      "Dabrafenib",
      "Vemurafenib",
      "Cobimetinib",
      "Selumetinib",
      "Pazopanib",
      "Sunitinib",
      "Sorafenib",
      "Axitinib",
      "Regorafenib",
      "Lenvatinib",
      "Atezolizumab",
      "Durvalumab",
      "Nivolumab",
      "Pembrolizumab",
      "Ipilimumab",
      "Mefloquine",
      "Atovaquone/Proguanil",
      "Chloroquine",
      "Quinine",
      "Artemether/Lumefantrine",
      "Doxycycline",
      "Primaquine",
      "Malarone",
      "Hydroxychloroquine",
      "Amanita muscaria",
      "Dexamethasone",
      "Griseofulvin",
      "Fluconazole",
      "Voriconazole",
      "Liposomal amphotericin B",
      "Caspofungin",
      "Micafungin",
      "Anidulafungin",
      "Nystatin",
      "Terbinafine",
      "Zidovudine",
      "Didanosine",
      "Stavudine",
      "Zalcitabine",
      "Lopinavir/ritonavir",
      "Efavirenz",
      "Nevirapine",
      "Saquinavir",
      "Indinavir",
      "Nelfinavir",
      "Tipranavir",
      "Fosamprenavir",
      "Rilpivirine",
      "Elvitegravir",
      "Dolutegravir",
      "Bictegravir",
      "Maraviroc",
      "Enfuvirtide",
      "Cobicistat",
      "Tenofovir",
      "Adefovir",
      "Emtricitabine",
      "Lamivudine",
      "Abacavir",
      "Truvada",
      "Descovy",
      "HIV-1 protease inhibitors",
      "NRTIs",
      "NNRTIs",
      "Integrase inhibitors",
      "Entry inhibitors",
      "Fusion inhibitors",
      "HCV direct-acting antiviral agents",
      "Simeprevir",
      "Sofosbuvir",
      "Ledipasvir",
      "Velpatasvir",
      "Glecaprevir",
      "Pibrentasvir",
      "Ribavirin",
      "Interferon alpha",
      "Peginterferon",
      "Fingolimod",
      "Dimethyl fumarate",
      "Teriflunomide",
      "Natalizumab",
      "Ocrelizumab",
      "Alemtuzumab",
      "Rituximab",
      "Mitoxantrone",
      "Dalfampridine",
      "Cladribine",
      "OnabotulinumtoxinA",
      "Baclofen",
      "Gabapentin",
      "Pregabalin",
      "Carbamazepine",
      "Phenytoin",
      "Divalproex sodium",
      "Lamotrigine",
      "Topiramate",
      "Zonisamide",
      "Levetiracetam",
      "Lacosamide",
      "Rufinamide",
      "Eslicarbazepine",
      "Perampanel",
      "Valproate",
      "Ethosuximide",
      "Cannabidiol",
      "Benzodiazepines",
      "Clonazepam",
      "Diazepam",
      "Lorazepam",
      "Alprazolam",
      "Clobazam",
      "Chlordiazepoxide",
      "Flurazepam",
      "Temazepam",
      "Midazolam",
      "Oxazepam",
      "Triazolam",
      "Buspirone",
      "Doxepin",
      "Amitriptyline",
      "Nortriptyline",
      "Desipramine",
      "Imipramine",
      "Clomipramine",
      "Trimipramine",
      "Mirtazapine",
      "Trazodone",
      "Duloxetine",
      "Venlafaxine",
      "Fluoxetine",
      "Citalopram",
      "Escitalopram",
      "Paroxetine",
      "Sertraline",
      "Bupropion",
      "St. John's wort",
      "L-tryptophan",
      "S-adenosylmethionine",
      "Omega-3 fatty acids",
      "5-HTP",
      "L-methylfolate",
      "Lithium",
      "Aripiprazole",
      "Quetiapine",
      "Olanzapine",
      "Risperidone",
      "Ziprasidone",
      "Clozapine",
      "Paliperidone",
      "Brexpiprazole",
      "Cariprazine",
      "Lurasidone",
      "Asenapine",
      "Chlorpromazine",
      "Thioridazine",
      "Haloperidol",
      "Fluphenazine",
      "Perphenazine",
      "Trifluoperazine",
      "Molindone",
      "Loxapine",
      "Prochlorperazine",
      "Thiothixene",
      "Pimozide",
      "Olanzapine/Fluoxetine",
      "Ziprasidone",
      "Naltrexone",
      "Naloxone",
      "Methadone",
      "Buprenorphine",
      "Suboxone",
      "Varenicline",
      "Acamprosate",
      "Disulfiram",
      "Topiramate",
      "Gabapentin",
      "Pregabalin",
      "Lofexidine",
      "Clonidine",
      "Dexmedetomidine",
      "Nitrous oxide",
      "Ketamine",
      "Propofol",
      "Thiopental",
      "Etomidate",
      "Dexmedetomidine",
      "Fentanyl",
      "Sufentanil",
      "Remifentanil",
      "Morphine",
      "Hydromorphone",
      "Oxycodone",
      "Hydrocodone",
      "Methadone",
      "Tramadol",
      "Codeine",
      "Meperidine",
      "Tapentadol",
      "Buprenorphine",
      "Loperamide",
      "Diphenoxylate/Atropine",
      "Dextromethorphan",
      "Baclofen",
      "Zolpidem",
      "Eszopiclone",
      "Suvorexant",
      "Ramelteon",
      "Melatonin",
      "Valerian root",
      "Chamomile",
      "Passionflower",
      "Lavender",
      "St. John's wort",
      "Kava kava",
      "Ginkgo biloba",
      "5-HTP",
      "L-tryptophan",
      "Taurine",
      "Magnesium",
      "Omega-3 fatty acids",
      "Coenzyme Q10",
      "Resveratrol",
      "Curcumin",
      "Glutathione",
      "N-acetylcysteine",
      "Vitamin D",
      "Vitamin B12",
      "Folic acid",
      "Zinc",
      "Selenium",
      "Iron",
      "Calcium",
      "Potassium",
      "Sodium",
      "Chloride",
      "Magnesium",
      "Phosphate",
      "Choline",
      "Inositol",
      "Vitamin A",
      "Vitamin C",
      "Vitamin E",
      "Vitamin K",
      "Probiotics",
      "Prebiotics",
      "Digestive enzymes",
      "Omega-3 fish oil",
      "Alpha-lipoic acid",
      "Quercetin",
      "Turmeric",
      "Milk thistle",
      "Ginger",
      "Echinacea",
      "Garlic",
      "Onion",
      "Thyme",
      "Oregano",
      "Rosemary",
      "Basil",
      "Cinnamon",
      "Cloves",
      "Black seed oil",
      "Grapeseed extract",
      "Pomegranate extract",
      "Green tea extract",
      "Hyaluronic acid",
      "L-Carnitine",
      "Creatine",
      "Beta-alanine",
      "Arginine",
      "Citrulline",
      "Glutamine",
      "BCAAs",
      "HMB",
      "D-Aspartic acid",
      "Testosterone boosters",
      "DHT blockers",
      "Hair growth supplements",
      "Collagen",
      "Biotin",
      "Keratin",
      "Astaxanthin",
      "Lutein",
      "Zeaxanthin",
      "Bacopa monnieri",
      "Rhodiola rosea",
      "Ashwagandha",
      "Holy basil",
      "Schisandra",
      "Cordyceps",
      "Lion's mane",
      "Reishi",
      "Chaga",
      "Maitake",
      "Shiitake",
      "Turkey tail",
      "Agaricus blazei",
      "Enoki",
      "Oyster",
      "Cordonopsis",
      "Ginseng",
      "Siberian ginseng",
      "Panax ginseng",
      "American ginseng",
      "Guarana",
      "Cacao",
      "Ginger",
      "Turmeric",
      "Ginkgo biloba",
      "Rhodiola rosea",
      "L-arginine",
      "L-citrulline",
      "Acetyl L-carnitine",
      "Glutathione",
      "N-acetylcysteine",
      "R-alpha lipoic acid",
      "Astaxanthin",
      "Selenium",
      "Zinc",
      "Vitamin D",
      "Vitamin C",
      "Vitamin A",
      "Vitamin E",
      "CoQ10",
      "Omega-3 fatty acids",
      "Krill oil",
      "Flaxseed oil",
      "Fish oil",
      "Algal oil",
      "Evening primrose oil",
      "Black seed oil",
      "Saw palmetto",
      "Stinging nettle",
      "Pumpkin seed oil",
      "Hyaluronic acid",
      "Vitamin K2",
      "Folate",
      "Biotin",
      "L-Theanine",
      "5-HTP",
      "Tryptophan",
      "Magnesium",
      "Potassium",
      "Calcium",
      "Sodium",
      "Chloride",
      "Phosphate",
      "Lysine",
      "Threonine",
      "Serine",
      "Methionine",
      "Leucine",
      "Isoleucine",
      "Valine",
      "Histidine",
      "Phenylalanine",
      "Taurine",
      "Creatine",
      "DHEA",
      "Testosterone",
      "Pregnenolone",
      "Androstenedione",
      "Dehydroepiandrosterone",
      "Estrone",
      "Estradiol",
      "Progesterone",
      "Thyroid hormones",
      "Adrenal hormones",
      "Insulin",
      "Glucagon",
      "Vasopressin",
      "Calcitonin",
      "Parathyroid hormone",
      "Oxytocin",
      "Prolactin",
      "Somatotropin",
      "Melatonin",
      "Histamine",
      "Serotonin",
      "Dopamine",
      "Norepinephrine",
      "Epinephrine",
      "Acetylcholine",
      "Gamma-aminobutyric acid",
      "Endorphins",
      "Enkephalins",
      "Substance P",
      "Neuropeptide Y",
      "Leptin",
      "Ghrelin",
      "Cholecystokinin",
      "Glucose-dependent insulinotropic peptide",
      "Peptide YY",
      "Neurotensin",
      "Calcitonin gene-related peptide",
      "Vasoactive intestinal peptide",
      "Atrial natriuretic peptide",
      "Brain natriuretic peptide",
      "Corticotropin-releasing hormone",
      "Thyrotropin-releasing hormone",
      "Luteinizing hormone",
      "Follicle-stimulating hormone",
      "Adrenocorticotropic hormone",
      "Growth hormone-releasing hormone",
      "Melanocyte-stimulating hormone",
      "Oxytocin",
      "Antidiuretic hormone",
      "Prolactin",
      "Thyroid-stimulating hormone",
      "Insulin-like growth factor",
      "Thymosin",
      "Gastrin",
      "Secretin",
      "Somatostatin",
      "Insulin-like peptides",
      "Adiponectin",
      "Resistin",
      "Tumor necrosis factor",
      "Interleukins",
      "Interferons",
      "Transforming growth factor",
      "Platelet-derived growth factor",
      "Fibroblast growth factor",
      "Vascular endothelial growth factor",
      "Hepatocyte growth factor",
      "Nerve growth factor",
      "Epidermal growth factor",
      "Insulin-like growth factor",
      "Neurotrophic factors",
      "Glycoprotein hormones",
      "Prostaglandins",
      "Leukotrienes",
      "Thromboxanes",
      "Lipoxins",
      "Endocannabinoids",
      "Nitric oxide",
      "Carbon monoxide",
      "Hydrogen sulfide",
      "Endothelins",
      "Cytokines",
      "Chemokines",
      "Pathogens",
      "Viruses",
      "Bacteria",
      "Fungi",
      "Parasites",
      "Prions",
      "Toxins",
      "Allergens",
      "Antigens",
      "Antibodies",
      "Inflammatory mediators",
      "Immune cells",
      "Cytokines",
      "Interleukins",
      "Tumor necrosis factor",
      "Complement proteins",
      "Histamine",
      "Mast cells",
      "Macrophages",
      "T cells",
      "B cells",
      "Natural killer cells",
      "Dendritic cells",
      "Neutrophils",
      "Eosinophils",
      "Basophils",
      "Monocytes",
      "Granulocytes",
      "Lymphocytes",
      "Cytotoxic T cells",
      "Helper T cells",
      "Regulatory T cells",
      "Memory T cells",
      "Memory B cells",
      "Plasma cells",
      "Antigen-presenting cells",
      "Immune complexes",
      "Immunoglobulins",
      "IgG",
      "IgM",
      "IgA",
      "IgE",
      "IgD",
      "Cellular immunity",
      "Humoral immunity",
      "Adaptive immunity",
      "Innate immunity",
      "Autoimmunity",
      "Hypersensitivity",
      "Immunodeficiency",
      "Vaccines",
      "Adjuvants",
      "Immunomodulators",
      "Immunotherapy",
      "Biologics",
      "Monoclonal antibodies",
      "Cytokine inhibitors",
      "Checkpoint inhibitors",
      "CAR T-cell therapy",
      "Gene therapy",
      "Cell therapy",
      "Stem cell therapy",
      "Transplantation",
      "Immunosuppressants",
      "Immunostimulants",
      "Immunoadjuvants",
      "Immunotherapeutic agents",
      "Vaccines",
      "Toxoids",
      "Antitoxins",
      "Immunoglobulins",
      "Monoclonal antibodies",
      "Hyperimmune globulin",
      "Cytokines",
      "Interferons",
      "Interleukins",
      "Colony-stimulating factors",
      "Chemokines",
      "Growth factors",
      "Antigen-presenting cells",
      "Macrophages",
      "Dendritic cells",
      "B cells",
      "T cells",
      "Natural killer cells",
      "Regulatory T cells",
      "Memory T cells",
      "Memory B cells",
      "Plasma cells",
      "Cytotoxic T cells",
      "Helper T cells",
      "Immune complexes",
      "Immunoglobulins",
      "IgG",
      "IgM",
      "IgA",
      "IgE",
      "IgD",
      "Complement proteins",
      "Mast cells",
      "Basophils",
      "Eosinophils",
      "Neutrophils",
      "Monocytes",
      "Granulocytes",
      "Lymphocytes",
    ];

    // print(drugs.length);
    for (int i = 0; i < drugs.length; i++) {
      String name = drugs[i];
      int rate = random.nextInt(100) + 1; // Random rate between 1 and 100
      int stock = random.nextInt(500) + 1; // Random stock between 1 and 500
      String date =
          DateTime.now().toIso8601String(); // Current date as ISO string

      Product product = Product(
        // id: id,
        name: name,
        date: date,
        rate: rate,
        stock: stock,
        currentStock: stock,
        outStock: 0,
      );
      // Insert product into the database
      await dbHelper.insertProduct(product);
      print('Inserted $i'); // Optional: Print to verify insertion
    }
  }

  Future<int> addProduct(nameController, rateController, stockController,
      databaseHelper, BuildContext context) async {
    // final int id = int.tryParse(idController.text) ?? 0;
    final String name = nameController.text;
    int rate = int.tryParse(rateController.text) ?? 0;
    int stock = int.tryParse(stockController.text) ?? 0;
    DateTime currentDate = DateTime.now();
    String date = DateFormat('dd-MM-yyyy').format(currentDate);

    final Product product = Product(
      // id: id,
      name: name,
      date: date,
      rate: rate,
      stock: stock,
      currentStock: stock,
      outStock: 0,
    );

    return await databaseHelper.insertProduct(product);

    // myAlert();
  }
}
